### ISSUE TITLE
Personnavne

### ISSUE THREAD

**Issue by thsh77** [dsldk/henrik-smith#3]
Der skal etableres et register over de i lægebøgerne forekommende personnavne. Indtil retningslinjerne publiceres følges denne (midlertidige) fremgangsmåde:

The index of personal names in DL is encoded in the [TOML](https://toml.io/en/) format as
tables containing key/value pairs. Each note follows this form:

```toml
[n1]               # <- a table definition
key = "value"      # <- a key/value pair
```

## Format

Each table has this format:

table definition
: A string consisting of `surname_firstname_birthyear`. Please note
that only lower-case characters `a-z` may be used.

name
: Given name with first name and surname. This is the name displayed to the reader

sortname
: The value of this key is used for sorting and display in alphabetical indexes.

lifetime
: If known the date of birth and date of death

description
: Short biography of the person in question

An example

```toml
[brandes_edvard_1847]
name = "Edvard Brandes"
sortname = "Brandes, Edvard"
lifetime = "1847-1931"
description = "forfatter, dramatiker, journalist og teaterkritiker, politiker, redaktør og medstifter 1884 af dagbladet Politiken"
```

The text content in the value of the description key is encoded in Markdown format. The following
conventions apply:

### Emphasis

To emphasize some text, surround it with * (asterisks) or _
(underscores) like this:

```md
This text is _emphasized with underscores_, and this
is *emphasized with asterisks*.
```

Double * or _ produces strong emphasis:

```md
This is **strong emphasis** and __with underscores__.
```

A * or _ character surrounded by spaces, or backslash-escaped, will not trigger emphasis:

```md
This is * not emphasized *, and \*neither is this\*.
```
